# Secrets that can be mounted by a keeper pod
# see http://kubernetes.io/docs/user-guide/secrets/

apiVersion: v1
kind: Secret
metadata:
  name: keeper-secrets
type: Opaque
data:
  # Each secret value must be base64 encoded.
  # e.g. `echo -n hello | base64 | pbcopy`
  secret-key: FIXME
  aws-id: FIXME
  aws-secret: FIXME
  default-user: FIXME
  default-password: FIXME
  server-name: FIXME
  preferred-url-scheme: FIXME
